/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_o2xfs_xfs_spi_std_core_Win32MessageQueue */

#ifndef _Included_at_o2xfs_xfs_spi_std_core_Win32MessageQueue
#define _Included_at_o2xfs_xfs_spi_std_core_Win32MessageQueue
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_o2xfs_xfs_spi_std_core_Win32MessageQueue
 * Method:    postMessage0
 * Signature: ([BJ[B)V
 */
JNIEXPORT void JNICALL Java_at_o2xfs_xfs_spi_std_core_Win32MessageQueue_postMessage0
  (JNIEnv *, jobject, jbyteArray, jlong, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
